import { SkinTone, PartCategory, FacePartOption, PartTransform, Gender } from './types';

export const SKIN_TONES: SkinTone[] = [
  { id: 'pale', name: 'Pale Light', fill: '#fbe3d4', shadow: '#e5bda7', highlight: '#ffffff' },
  { id: 'fair', name: 'Fair Natural', fill: '#f6d5c1', shadow: '#dcae95', highlight: '#fff2e9' },
  { id: 'medium', name: 'Warm Medium', fill: '#e4b693', shadow: '#ca946e', highlight: '#f3d6c1' },
  { id: 'olive', name: 'Olive Golden', fill: '#c9966b', shadow: '#ab764b', highlight: '#dcab82' },
  { id: 'tan', name: 'Warm Tan', fill: '#b27b50', shadow: '#8f5c34', highlight: '#c79165' },
  { id: 'dark', name: 'Rich Brown', fill: '#734629', shadow: '#512f17', highlight: '#8a593a' },
  { id: 'deep-dark', name: 'Deep Ebony', fill: '#3d2314', shadow: '#221108', highlight: '#54321d' },
  { id: 'forensic-monochrome', name: 'Forensic Wireframe', fill: '#1e293b', shadow: '#0f172a', highlight: '#334155' },
  { id: 'cyber-cyan', name: 'Tactical Blueprint', fill: '#0f2b38', shadow: '#061720', highlight: '#17475d' },
];

export const DEFAULT_TRANSFORMS: Record<PartCategory, PartTransform> = {
  head: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: 0, spacing: 0, color: '#000000', opacity: 1 },
  hair: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: 0, spacing: 0, color: '#2a1a08', opacity: 1 },
  eyebrows: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: 0, spacing: 0, color: '#2a1a08', opacity: 1 },
  eyes: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: 0, spacing: 0, color: '#4a2e12', opacity: 1 },
  nose: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: 0, spacing: 0, color: '#000000', opacity: 1 },
  mouth: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: 0, spacing: 0, color: '#b05d5d', opacity: 1 },
  ears: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: 0, spacing: 0, color: '#000000', opacity: 1 },
  beard: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: 0, spacing: 0, color: '#2a1a08', opacity: 0.9 },
  glasses: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: 0, spacing: 0, color: '#1e293b', opacity: 1 },
  marks: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: 0, spacing: 0, color: '#7a3e3e', opacity: 0.8 },
};

export const PART_OPTIONS: Record<PartCategory, FacePartOption[]> = {
  head: [
    { id: 'head-oval', name: 'Classic Oval', category: 'head', description: 'Balanced proportioned structure' },
    { id: 'head-square', name: 'Chiseled Square', category: 'head', genderAllowed: ['male', 'androgynous'], description: 'Strong angular jawline' },
    { id: 'head-round', name: 'Soft Round', category: 'head', description: 'Smooth rounded cheeks & jaw' },
    { id: 'head-heart', name: 'Tapered Heart', category: 'head', description: 'Broader forehead with delicate chin' },
    { id: 'head-diamond', name: 'Sharp Diamond', category: 'head', description: 'High cheekbones with narrow chin' },
    { id: 'head-chiseled', name: 'Tactical Chiseled', category: 'head', genderAllowed: ['male'], description: 'Heavy prominent jawline' },
  ],
  hair: [
    { id: 'hair-short-crop', name: 'Short Executive Crop', category: 'hair', genderAllowed: ['male', 'androgynous'] },
    { id: 'hair-buzz-cut', name: 'Tactical Buzz Cut', category: 'hair', genderAllowed: ['male', 'androgynous'] },
    { id: 'hair-side-part', name: 'Classic Side Part', category: 'hair' },
    { id: 'hair-slick-back', name: 'Slick Back', category: 'hair' },
    { id: 'hair-pompadour', name: 'Modern Pompadour / Quiff', category: 'hair' },
    { id: 'hair-spiky-top', name: 'Textured Spiky Crop', category: 'hair' },
    { id: 'hair-man-bun', name: 'Top Knot / Man Bun', category: 'hair' },
    { id: 'hair-messy-fringe', name: 'Messy Forward Fringe', category: 'hair' },
    { id: 'hair-curly-afro', name: 'Voluminous Curly Afro', category: 'hair' },
    { id: 'hair-long-waves', name: 'Flowing Waves', category: 'hair', genderAllowed: ['female', 'androgynous'] },
    { id: 'hair-ponytail', name: 'Sleek High Ponytail', category: 'hair', genderAllowed: ['female', 'androgynous'] },
    { id: 'hair-pixie', name: 'Tapered Pixie Cut', category: 'hair', genderAllowed: ['female', 'androgynous'] },
    { id: 'hair-braids', name: 'Top Braids / Dreadlocks', category: 'hair' },
    { id: 'hair-dreadlocks', name: 'Full Long Dreadlocks', category: 'hair' },
    { id: 'hair-receding', name: 'Receding Hairline', category: 'hair', genderAllowed: ['male'] },
    { id: 'hair-bald', name: 'Fully Shaved / Bald', category: 'hair' },
    { id: 'hair-bob', name: 'Structured Sleek Bob', category: 'hair', genderAllowed: ['female'] },
    { id: 'hair-widows-peak', name: 'Executive Widow Peak', category: 'hair', genderAllowed: ['male', 'androgynous'] },
    { id: 'hair-silver-curls', name: 'Curled Silver Afro Ringlets', category: 'hair' },
    { id: 'hair-sleek-bangs', name: 'Glamour Front Bangs & Bob', category: 'hair', genderAllowed: ['female', 'androgynous'] },
    { id: 'hair-taper-fade', name: 'Presidential Taper Fade', category: 'hair', genderAllowed: ['male', 'androgynous'] },
    { id: 'hair-shoulder-flow', name: 'Slick Medium Flow (John Wick)', category: 'hair' },
    { id: 'hair-peaky-undercut', name: 'Vintage 1920s Undercut', category: 'hair' },
    { id: 'hair-wild-einstein', name: 'Unruly Theoretical Afro', category: 'hair' },
    { id: 'hair-braided-updo', name: 'Athletic Braided Top Crown', category: 'hair', genderAllowed: ['female', 'androgynous'] },
    { id: 'hair-sleek-slickback', name: 'Hollywood Classic Slicked Back', category: 'hair' },
  ],
  eyebrows: [
    { id: 'eyebrow-classic', name: 'Natural Medium Arch', category: 'eyebrow' as any },
    { id: 'eyebrow-thin-arch', name: 'Elevated Arched', category: 'eyebrow' as any },
    { id: 'eyebrow-bushy', name: 'Heavy Bushy', category: 'eyebrow' as any },
    { id: 'eyebrow-angular', name: 'Sharp Tactical Angular', category: 'eyebrow' as any },
    { id: 'eyebrow-straight', name: 'Low Straight Brows', category: 'eyebrow' as any },
    { id: 'eyebrow-unibrow', name: 'Joined Thick Unibrow', category: 'eyebrow' as any },
    { id: 'eyebrow-slanted-v', name: 'Slanted Aggressive V-Shape', category: 'eyebrow' as any },
    { id: 'eyebrow-plucked-thin', name: 'Ultra-Thin Pencil Eyebrow', category: 'eyebrow' as any },
    { id: 'eyebrow-high-arch', name: 'High Arch Glamour Brows', category: 'eyebrow' as any },
    { id: 'eyebrow-feathered', name: 'Soft Feathered Natural', category: 'eyebrow' as any },
    { id: 'eyebrow-scarred', name: 'Brows with Scar Gap', category: 'eyebrow' as any },
  ],
  eyes: [
    { id: 'eyes-almond', name: 'Symmetrical Almond', category: 'eyes' },
    { id: 'eyes-round', name: 'Expressive Round', category: 'eyes' },
    { id: 'eyes-hooded', name: 'Deep-Set Hooded', category: 'eyes' },
    { id: 'eyes-monolid', name: 'Sleek Monolid', category: 'eyes' },
    { id: 'eyes-cat-eye', name: 'Cat-Eye Lifted Corners', category: 'eyes' },
    { id: 'eyes-deep-shadow', name: 'Intense Deep-Set Shadowed', category: 'eyes' },
    { id: 'eyes-wide-pupil', name: 'Alert Wide Open Pupil', category: 'eyes' },
    { id: 'eyes-droopy-lid', name: 'Droopy Heavy Eyelids', category: 'eyes' },
    { id: 'eyes-squinting', name: 'Tactical Narrow Squint', category: 'eyes' },
    { id: 'eyes-intense', name: 'Narrowed Tactical Gaze', category: 'eyes' },
    { id: 'eyes-downturned', name: 'Downturned Outer Corners', category: 'eyes' },
  ],
  nose: [
    { id: 'nose-straight', name: 'Classic Straight Bridge', category: 'nose' },
    { id: 'nose-button', name: 'Petite Button Nose', category: 'nose' },
    { id: 'nose-crooked', name: 'Broken / Crooked Bridge', category: 'nose' },
    { id: 'nose-upturned', name: 'Upturned Button Nose', category: 'nose' },
    { id: 'nose-roman', name: 'Strong Roman Ridge', category: 'nose' },
    { id: 'nose-bulbous', name: 'Bulbous Round Tip', category: 'nose' },
    { id: 'nose-wide-flat', name: 'Wide Flat Nostrils', category: 'nose' },
    { id: 'nose-aquiline', name: 'Aquiline / Hooked Bridge', category: 'nose' },
    { id: 'nose-broad', name: 'Broad Nostrils', category: 'nose' },
    { id: 'nose-pointed', name: 'Prominent Pointed Tip', category: 'nose' },
  ],
  mouth: [
    { id: 'mouth-neutral', name: 'Relaxed Natural Lips', category: 'mouth' },
    { id: 'mouth-full', name: 'Plump Full Lips', category: 'mouth' },
    { id: 'mouth-thin', name: 'Stern Narrow Line', category: 'mouth' },
    { id: 'mouth-smirk', name: 'Asymmetric Cocky Smirk', category: 'mouth' },
    { id: 'mouth-grin', name: 'Wide Open Grin', category: 'mouth' },
    { id: 'mouth-pout', name: 'Pouting Lips', category: 'mouth' },
    { id: 'mouth-thick-upper', name: 'Thick Upper Lip', category: 'mouth' },
    { id: 'mouth-grimace', name: 'Stern Tight Grimace', category: 'mouth' },
    { id: 'mouth-smile', name: 'Subtle Confident Smile', category: 'mouth' },
    { id: 'mouth-cupid', name: 'Defined Cupid\'s Bow', category: 'mouth' },
    { id: 'mouth-downturned', name: 'Serious Downturned Lips', category: 'mouth' },
  ],
  ears: [
    { id: 'ears-classic', name: 'Standard Proportioned', category: 'ears' },
    { id: 'ears-protruding', name: 'Protruding Outer Flare', category: 'ears' },
    { id: 'ears-pointed', name: 'Pointed Tapered Elf Ears', category: 'ears' },
    { id: 'ears-cauliflower', name: 'Rugby / Cauliflower Ear', category: 'ears' },
    { id: 'ears-attached', name: 'Attached Flat Lobe', category: 'ears' },
    { id: 'ears-pierced', name: 'Pierced Lobe with Ring', category: 'ears' },
    { id: 'ears-small', name: 'Compact Attached Lobe', category: 'ears' },
    { id: 'ears-long', name: 'Elongated Lobe', category: 'ears' },
  ],
  beard: [
    { id: 'beard-none', name: 'Clean Shaven (None)', category: 'beard' },
    { id: 'beard-stubble', name: 'Heavy 5 o\'clock Stubble', category: 'beard', genderAllowed: ['male'] },
    { id: 'beard-full', name: 'Rugged Full Beard', category: 'beard', genderAllowed: ['male'] },
    { id: 'beard-goatee', name: 'Trimmed Goatee & Stache', category: 'beard', genderAllowed: ['male'] },
    { id: 'beard-handlebar', name: 'Handlebar Mustache', category: 'beard', genderAllowed: ['male'] },
    { id: 'beard-pencil', name: 'Pencil Thin Mustache', category: 'beard', genderAllowed: ['male'] },
    { id: 'beard-full-rugged', name: 'Rugged Hollywood Full Beard', category: 'beard', genderAllowed: ['male'] },
    { id: 'beard-stubble-chin', name: 'Defined Jawline Stubble', category: 'beard', genderAllowed: ['male'] },
  ],
  glasses: [
    { id: 'glasses-none', name: 'No Eyewear', category: 'glasses' },
    { id: 'glasses-rectangle', name: 'Tech Rectangular Frames', category: 'glasses' },
    { id: 'glasses-round', name: 'Wireframe Round Glasses', category: 'glasses' },
    { id: 'glasses-tactical', name: 'Dark Tactical Aviators', category: 'glasses' },
    { id: 'glasses-rimless-round', name: 'Minimalist Rimless Round Specs', category: 'glasses' },
    { id: 'glasses-classic-wayfarer', name: 'Classic Dark Wayfarers', category: 'glasses' },
  ],
  marks: [
    { id: 'marks-none', name: 'No Facial Marks', category: 'marks' },
    { id: 'marks-cheek-scar', name: 'Diagonal Cheek Scar', category: 'marks' },
    { id: 'marks-eyebrow-scar', name: 'Vertical Brow Cut', category: 'marks' },
    { id: 'marks-mole-cheek', name: 'Prominent Cheek Mole', category: 'marks' },
    { id: 'marks-freckles', name: 'Cheek & Nose Freckles', category: 'marks' },
    { id: 'marks-chin-cleft', name: 'Distinctive Cleft Chin', category: 'marks' },
    { id: 'marks-cheek-dimples', name: 'Cheek Smile Dimples', category: 'marks' },
    { id: 'marks-beauty-mole', name: 'Lip Beauty Mark', category: 'marks' },
    { id: 'marks-stubble-salt-pepper', name: 'Salt & Pepper Jaw Shading', category: 'marks' },
  ],
};
